In [1]:
import numpy as np

In [4]:
p=np.random.rand(4,3)
s=np.array([1,2,3])
p

array([[0.32610406, 0.35103563, 0.79526799],
       [0.13909722, 0.0207083 , 0.3737932 ],
       [0.34687439, 0.28607051, 0.39965975],
       [0.13889223, 0.35693911, 0.88694384]])

In [8]:
p.sum(axis=1,keepdims=1)

array([[1.47240769],
       [0.53359871],
       [1.03260464],
       [1.38277519]])

In [11]:
p[:,0][:,None]

array([[0.32610406],
       [0.13909722],
       [0.34687439],
       [0.13889223]])