In [1]:
import numpy as np


In [2]:
arr1=np.array([0,0,1,1,1,1,0,0,2,2,2])
arr1

array([0, 0, 1, 1, 1, 1, 0, 0, 2, 2, 2])

In [4]:
arr2=np.zeros_like(arr1)
arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr2[arr1==0]=1
arr2[arr1==1]=2
arr2

array([1, 1, 2, 2, 2, 2, 1, 1, 0, 0, 0])

In [14]:
a1,b1=np.unique(arr1,return_counts=1)
a2,b2=np.unique(arr2,return_counts=1)

pc1=dict(zip(a1,b1))
pc1

{0: 4, 1: 4, 2: 3}

In [15]:
pc2=dict(zip(a2,b2))
pc2

{0: 3, 1: 4, 2: 4}

In [17]:
sorted(pc1.items(),key=lambda x:x[1])

[(2, 3), (0, 4), (1, 4)]

In [18]:
sorted(pc2.items(),key=lambda x:x[1])

[(0, 3), (1, 4), (2, 4)]