In [1]:
import numpy as np

In [5]:
data = np.array([[35, 176, 0, 20000, 0],
                 [28, 178, 1, 10000, 1],
                 [26, 172, 0, 25000, 0],
                 [29, 173, 2, 20000, 1],
        [         28, 174, 0, 15000, 1]])

In [19]:
data[np.where(data[:,2]<1)[0]]

array([[   35,   176,     0, 20000,     0],
       [   26,   172,     0, 25000,     0],
       [   28,   174,     0, 15000,     1]])

In [27]:
con=data[:,2]<1
data[con]

array([[   35,   176,     0, 20000,     0],
       [   26,   172,     0, 25000,     0],
       [   28,   174,     0, 15000,     1]])

In [28]:
data[~con]

array([[   28,   178,     1, 10000,     1],
       [   29,   173,     2, 20000,     1]])