In [2]:
import numpy as np
import pandas as pd

In [12]:
data=np.array([[0,0,1],
               [1,1,2],
               [2,2,0],
               [1,4,2]])



In [14]:
np.split(data,[-1],axis=1)

[array([[0, 0],
        [1, 1],
        [2, 2],
        [1, 4]]),
 array([[1],
        [2],
        [0],
        [2]])]

In [10]:
n=data[1]
n

array([1, 1, 2])

In [11]:
np.append(n,[1])

array([1, 1, 2, 1])