In [1]:
import numpy as np

In [2]:
data=np.random.rand(4,5)
data

array([[0.42271801, 0.17800213, 0.92690961, 0.49939755, 0.69514201],
       [0.01664452, 0.12388824, 0.61309453, 0.06523172, 0.49834667],
       [0.79498255, 0.84159081, 0.25191194, 0.75412213, 0.07197567],
       [0.529538  , 0.51555441, 0.83907575, 0.31453491, 0.81104061]])

In [4]:
np.divide(data,data.sum(axis=1)[:,None])

array([[0.15528718, 0.06538981, 0.34050403, 0.18345573, 0.25536325],
       [0.01263624, 0.09405383, 0.46545087, 0.04952281, 0.37833626],
       [0.29285622, 0.31002581, 0.09279949, 0.27780403, 0.02651445],
       [0.17594123, 0.17129512, 0.27878645, 0.10450555, 0.26947165]])

In [7]:
s=data.sum(axis=1,keepdims=1)
s

array([[2.72216931],
       [1.31720568],
       [2.7145831 ],
       [3.00974368]])

In [8]:
data[0,0]/s[0,0]

0.1552871839780284