In [1]:
import numpy as np

In [2]:
data=np.random.rand(12,3)
data

array([[0.13435018, 0.0662484 , 0.92311873],
       [0.63454   , 0.83664824, 0.32958678],
       [0.75831764, 0.02595873, 0.42894524],
       [0.81718118, 0.79095973, 0.21695175],
       [0.48970326, 0.76292347, 0.41571616],
       [0.48965406, 0.15206117, 0.0802254 ],
       [0.34081007, 0.53542763, 0.63897178],
       [0.8593878 , 0.61005054, 0.02054168],
       [0.79876034, 0.31850296, 0.71911465],
       [0.08014579, 0.57143506, 0.54727004],
       [0.75268261, 0.59737891, 0.80693573],
       [0.55863626, 0.4364929 , 0.70535954]])

In [3]:
def sony(data,batch):
    n=len(data)//batch
    ins=[batch*(i) for i in range(1,n+1)]
    if ins[-1]==len(data):
        ins.pop()
    print(ins)
    dat=np.split(data,ins,axis=0)

    return dat
sony(data,5)

[5, 10]


[array([[0.13435018, 0.0662484 , 0.92311873],
        [0.63454   , 0.83664824, 0.32958678],
        [0.75831764, 0.02595873, 0.42894524],
        [0.81718118, 0.79095973, 0.21695175],
        [0.48970326, 0.76292347, 0.41571616]]),
 array([[0.48965406, 0.15206117, 0.0802254 ],
        [0.34081007, 0.53542763, 0.63897178],
        [0.8593878 , 0.61005054, 0.02054168],
        [0.79876034, 0.31850296, 0.71911465],
        [0.08014579, 0.57143506, 0.54727004]]),
 array([[0.75268261, 0.59737891, 0.80693573],
        [0.55863626, 0.4364929 , 0.70535954]])]

In [4]:
x=np.random.rand(10)
x

array([0.65887217, 0.44398702, 0.56934741, 0.58281841, 0.96187559,
       0.16154952, 0.32999038, 0.91512215, 0.81838424, 0.35590102])

In [5]:
np.split(x,[2,6])

[array([0.65887217, 0.44398702]),
 array([0.56934741, 0.58281841, 0.96187559, 0.16154952]),
 array([0.32999038, 0.91512215, 0.81838424, 0.35590102])]

In [6]:
p=np.array([2.60073, 1.41727, 0.34905 ,0.371  , 0.68184])
l=[p[-1]]
l

[0.68184]

In [7]:
np.allclose(p,l)

False

In [11]:
x=np.random.randn(5,4)
x

array([[ 0.12349608, -0.47290977,  0.748175  , -0.55346134],
       [-0.33114523,  0.43686683, -0.15938036, -1.78322167],
       [-1.30388341,  0.86414789, -1.25792765,  0.91867009],
       [-0.94682023, -0.70892539,  1.49691201, -0.56194787],
       [ 1.33079981,  0.18235167, -0.30340244, -1.79514512]])

In [12]:
np.power(x,2)

array([[0.01525128, 0.22364365, 0.55976583, 0.30631945],
       [0.10965717, 0.19085262, 0.0254021 , 3.17987953],
       [1.70011195, 0.74675158, 1.58238197, 0.84395473],
       [0.89646854, 0.50257521, 2.24074557, 0.31578541],
       [1.77102814, 0.03325213, 0.09205304, 3.222546  ]])

In [13]:
0.74*0.74

0.5476