In [1]:
from collections import defaultdict,Counter
import numpy as np

In [2]:
arr1=np.array([0,1,1,2,0,1,1,0,2,2,2,2,2])
arr2=np.array([2,0,2,1,2,0,2,2,1,1,0,1,2])
res=Counter(zip(arr1,arr2))
res

Counter({(2, 1): 4, (0, 2): 3, (1, 0): 2, (1, 2): 2, (2, 0): 1, (2, 2): 1})

In [3]:
d=defaultdict(list)
for var in np.unique(arr1):
    for k,v in res.items():
        if k[0]==var:
            d[var].append([*k,v])
d

defaultdict(list,
            {0: [[0, 2, 3]],
             1: [[1, 0, 2], [1, 2, 2]],
             2: [[2, 1, 4], [2, 0, 1], [2, 2, 1]]})

In [4]:
inps=[]
for r in d.values():
    s=np.array(r)
    inps.append(s[np.argmax(s[:,2])])

inps=np.array(inps)
sp=dict(zip(inps[:,0],inps[:,1]))
sp


{0: 2, 1: 0, 2: 1}

In [5]:
arr3=np.array(list(map(lambda x:sp[x],arr1)))
arr3

array([2, 0, 0, 1, 2, 0, 0, 2, 1, 1, 1, 1, 1])

In [6]:
arr2

array([2, 0, 2, 1, 2, 0, 2, 2, 1, 1, 0, 1, 2])

In [7]:
(arr3==arr2).sum()/len(arr1)

0.6923076923076923

array([[0.38593514, 0.20384937, 0.29982134, 0.9821253 , 0.02059397],
       [0.39897563, 0.86913986, 0.08687057, 0.82605528, 0.50636821],
       [0.11345218, 0.30728299, 0.8917219 , 0.95166514, 0.02473985],
       [0.80800152, 0.93098954, 0.61470463, 0.41628792, 0.00845694],
       [0.85000083, 0.03823983, 0.30226059, 0.83416956, 0.13779471]])

In [15]:
data=np.array([[ 0 ,96 , 0 , 4,  0],
      [95 , 0 , 1 , 0,  4],
      [ 1 , 0 ,99 , 0,  0],
      [ 5 , 0 , 1 , 0, 94],
      [ 0 , 3 , 0 ,97,  0],])
data

array([[ 0, 96,  0,  4,  0],
       [95,  0,  1,  0,  4],
       [ 1,  0, 99,  0,  0],
       [ 5,  0,  1,  0, 94],
       [ 0,  3,  0, 97,  0]])

In [19]:
p=data.argmax(axis=0)
s=np.array(range(5))

In [22]:
dict(zip(s,p))

{0: 1, 1: 0, 2: 2, 3: 4, 4: 3}