In [1]:
import numpy as np

In [2]:
data=np.eye(5)
data

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
data[range(5),range(5)]=[1,2,3,4,5]
data

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [21]:
x=np.array([1,2,3])
c=np.array([[2],[4],[5]])
(x-c.T)

array([[-1, -2, -2]])

In [40]:
cc=np.array([1])
cb=np.array([[1],[2],[3]])
np.power(cc-cb,2).ravel()

array([0, 1, 4])

In [36]:
s=[1,2,3]
np.diag(s)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])